Add svnadmin verify check on first backup run

diff --git a/svn-backup2 b/svn-backup2
--- a/svn-backup2
+++ b/svn-backup2
@@ -8,6 +8,7 @@ VERSION="0.1.0"
 ###
 SVNBACKUP2_CONFIG_FILE="/etc/svn-backup2.conf"
 SVNBACKUP2_LOG_FILE="/var/log/svn-backup2.log"
+SVNBACKUP2_SVNADMIN_VERIFY_LOG_FILE="/var/log/svn-backup2_svnadmin_verify.log"
 SVNBACKUP2_BACKUP_STATE_PATH="/var/tmp/svn-backup2"
 
 ###
@@ -51,6 +52,11 @@ function check_and_create_paths() {
 
 	if [ ! -f ${SVNBACKUP2_LOG_FILE} ]; then
 		touch ${SVNBACKUP2_LOG_FILE}
+	fi
+
+	if [ ! -d ${SVNBACKUP2_CFG_REPOSITORIES_PATH} ]; then
+		mkdir -p ${SVNBACKUP2_CFG_REPOSITORIES_PATH} 
+		log "Created repositories path at ${SVNBACKUP2_CFG_REPOSITORIES_PATH}"
 	fi
 
 	if [ ! -d ${SVNBACKUP2_BACKUP_STATE_PATH} ]; then
@@ -112,6 +118,8 @@ function repository_store_state() {
 function repository_load_state() {
 	export REPO_STATE_FILE="${SVNBACKUP2_BACKUP_STATE_PATH}/${REPO_NAME}.state"
 	export REPO_BACKUP_FILE="${SVNBACKUP2_CFG_BACKUP_PATH}/${REPO_NAME}.svnbackup2"
+	export REPO_PATH="${SVNBACKUP2_CFG_REPOSITORIES_PATH}/${REPO_NAME}"
+
 	REPO_BACKUP_FILE_EXISTS=0
 
 	if [ ! -f ${REPO_STATE_FILE} ]; then
@@ -136,7 +144,18 @@ function repository_backup_integrity_check() {
 	REPO_CHECKSUM_OK=0
 
 	if [ ! -f "${REPO_BACKUP_FILE}" ]; then
-		log "No backup exists for ${REPO_NAME} repository, integrity check skipped"
+		log "Running svnadmin verify on database because this is the first time, this may take a while..."
+
+		svnadmin verify "${REPO_PATH}" | tee ${SVNBACKUP2_LOG_FILE}
+
+		if [ $? -eq 0 ]; then
+			log "svnadmin verify succesfully"
+		else
+			log "ERROR: svnadmin verify failed"
+		fi
+
+		log "WARNING: No backup exists for ${REPO_NAME} repository, backup file integrity check skipped"
+
 		return
 	fi
 
@@ -223,4 +242,4 @@ function repository_backup() {
 check_and_create_paths
 load_config_file
 
-repository_backup "test"
+repository_backup "testrepo1"
